env:
  es6: true
  node: true
  browser: true
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
parser: babel-eslint
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    impliedStrict: true
  sourceType: module
rules:
  comma-spacing:
    - error
  dot-location:
    - error
    - property
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  no-console: 0
  no-unused-vars:
    - warn
    - ignoreRestSiblings: true
      argsIgnorePattern: '^_'
  no-var:
    - error
  object-curly-spacing:
    - error
    - always
  prefer-const:
    - error
    - destructuring: all
      ignoreReadBeforeAssign: true
  quotes:
    - error
    - single
  semi:
    - error
    - never
  space-infix-ops:
    - error
  keyword-spacing:
    - error
  space-before-blocks:
    - error
  no-debugger:
    - warn
  key-spacing:
    - error
    - beforeColon : false
      afterColon : true
  no-constant-condition: ["error", { "checkLoops": false }]
